### PR TITLE
[23] fix acc and mag scaling factors and make them configurable

### LINKED ISSUE #23: [bug] Units break REP103 and are not consistent
We tried a view BNO055 driver for ROS2 and found a bug in all of them. To adhere to [REP 103](https://www.ros.org/reps/rep-0103.html) the messages have to use SI units.

In this package there are two problems:
 1. The acceleration factor is `1000` where it has to be `100`
 2. The magnetometer unit is in `μT` and not `T` the factor hast to be `16000000` and not `16`  

### The Bug
The `linear_acceleration` scale factor is set to `1000`, but has to be `100`.
From [the BNO055 Data Sheet](https://www.bosch-sensortec.com/media/boschsensortec/downloads/datasheets/bst-bno055-ds000.pdf):
- *3.6.1 Unit selection* - *Table 3-17: Accelerometer Unit settings*: 

|Unit|Representation| 
|:---|:---|
|m/s²| 1 m/s² = 100 LSB|
|mg| 1 mg = 1 LSB|

- *3.6.1 Unit selection* - *Table 3-19: Magnetometer Unit settings*:

|Unit|Representation| 
|:---|:---|
|μT| 1 μT = 16 LSB|

## Info
In the end, we decided to use the [ros2_bno055_driver from RoverRobotics-archive](https://github.com/RoverRobotics-archive/ros2_bno055_driver), because we only have an RPi4 and python is not that performant. Here are our fixes https://github.com/RoverRobotics-archive/ros2_bno055_driver/pull/6. But because this is the upstream repository of `ros-foxy-bno055`, it would be beneficial for other to fix it here as well.

### LINKED ISSUE #34: Usage of dash-seperated script-dir and install-scripts
```
Starting >>> bno055
/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'script-dir' will not be supported in future versions. Please use the underscore name 'script_dir' instead
  warnings.warn(
/home/ubuntu/.local/lib/python3.8/site-packages/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'install-scripts' will not be supported in future versions. Please use the underscore name 'install_scripts' instead
```

I believe `setup.cfg` should us underscores

```
[develop]
script_dir=$base/lib/bno055
[install]
install_scripts=$base/lib/bno055
```

### LINKED ISSUE #35: Runtime error: module 'bno055.registers' has no attribute 'START_BYTE_WR'
Tried using the module and I'm getting the following error:

```
[bno055]: Communication error: module 'bno055.registers' has no attribute 'START_BYTE_WR'
```

Looking at [registers.py](https://github.com/flynneva/bno055/blob/develop/bno055/registers.py) file it indeed does not contain a declaration for `START_BYTE_WR` (or `READ` also used by `Connector.py`) ?

Seems it got removed [here](https://github.com/flynneva/bno055/commit/04fd2ab650345e753e1d9a0921b2acad7a33049b#diff-b9db45e17abedb2256190b6dd7e673053ea3fa9435ac3037ae3fd94c4279963bL87) so I'm not sure how it's still supposed to work?

Reverted to an older commit and now it runs but now I'm stuck at `Configuring device...` but I guess this could be an issue on my end.

```
[INFO] [1636574878.842770372] [bno055]: Initializing parameters
[INFO] [1636574878.854439565] [bno055]: Parameters set to:
[INFO] [1636574878.856625748] [bno055]:         ros_topic_prefix:       "bno055/"
[INFO] [1636574878.858723302] [bno055]:         connection_type:        "uart"
[INFO] [1636574878.860794226] [bno055]:         uart_port:              "/dev/serial1"
[INFO] [1636574878.862778039] [bno055]:         uart_baudrate:          "115200"
[INFO] [1636574878.864799852] [bno055]:         uart_timeout:           "0.1"
[INFO] [1636574878.866828146] [bno055]:         frame_id:               "imu"
[INFO] [1636574878.868809385] [bno055]:         data_query_frequency:   "100"
[INFO] [1636574878.870805976] [bno055]:         calib_status_frequency: "0.1"
[INFO] [1636574878.872801919] [bno055]:         operation_mode:         "12"
[INFO] [1636574878.874782028] [bno055]:         placement_axis_remap:   "P0"
[INFO] [1636574878.876822175] [bno055]:         acc_offset:             "[65516, 165, 65512]"
[INFO] [1636574878.878812747] [bno055]:         mag_offset:             "[65460, 65182, 637]"
[INFO] [1636574878.880806115] [bno055]:         gyr_offset:             "[2, 65535, 65535]"
[INFO] [1636574878.883295502] [bno055]: Opening serial port: "/dev/serial1"...
[INFO] [1636574878.905222001] [bno055]: Configuring device...
```

### PR DESCRIPTION
**Pull request by flynneva**
Signed-off-by: Evan Flynn <evanflynn.msu@gmail.com>

- closes #23
- closes #34 
- closes #35

### CODE REVIEW

**Comment by flynneva** [comment]
@darkproduct could you look over these changes and let me know if they fix the issues you identified in #23?

**Comment by Darkproduct** [comment]
Yes, looking good from my side. I currently don't have access to hardware but I can check on Thursday if that's necessary.

**Comment by flynneva** [comment]
@Darkproduct yeah I haven't had access to hardware either but hopefully will later this week. I'll confirm later and report back.

**Comment by flynneva** [comment]
@kallaspriit if you have some time would be great to get your review. I think I have fixed the missing constants you mentioned in #35 but would love a second pair of eyes.  I'll test this branch on hardware tomorrow

**Comment by kallaspriit** [comment]
Thanks, will try to test later today :)

**Comment by kallaspriit** [comment]
Hey, I can confirm that given branch compiles without issues and communication with Adafruit BNO055 is working nicely (testing on Raspberry PI 4B, Ubuntu server 20.04, uart5).

Only problem is that during startup I'm consistently getting six `Receiving sensor data failed with ZeroDivisionError:"float division by zero"` warnings and after that it seems to work fine (getting data on `/imu` topic). Somewhere it's probably trying to divide by zero but does not log the stack trace.

```
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [bno055-1]: process started with pid [3517]
[bno055-1] [INFO] [1636651512.736648900] [bno055]: Initializing parameters
[bno055-1] [INFO] [1636651512.752603194] [bno055]: Parameters set to:
[bno055-1] [INFO] [1636651512.755413902] [bno055]:      ros_topic_prefix:       ""
[bno055-1] [INFO] [1636651512.758326944] [bno055]:      connection_type:        "uart"
[bno055-1] [INFO] [1636651512.760868316] [bno055]:      uart_port:              "/dev/ttyAMA1"
[bno055-1] [INFO] [1636651512.763388485] [bno055]:      uart_baudrate:          "115200"
[bno055-1] [INFO] [1636651512.765895597] [bno055]:      uart_timeout:           "0.1"
[bno055-1] [INFO] [1636651512.768630268] [bno055]:      frame_id:               "imu"
[bno055-1] [INFO] [1636651512.771115676] [bno055]:      data_query_frequency:   "100"
[bno055-1] [INFO] [1636651512.773650382] [bno055]:      calib_status_frequency: "0.1"
[bno055-1] [INFO] [1636651512.776171532] [bno055]:      operation_mode:         "12"
[bno055-1] [INFO] [1636651512.778656552] [bno055]:      placement_axis_remap:   "P0"
[bno055-1] [INFO] [1636651512.781175553] [bno055]:      acc_factor:             "100.0"
[bno055-1] [INFO] [1636651512.783697648] [bno055]:      mag_factor:             "16000000.0"
[bno055-1] [INFO] [1636651512.786188464] [bno055]:      gyr_factor:             "900.0"
[bno055-1] [INFO] [1636651512.788727947] [bno055]:      acc_offset:             "[65516, 165, 65512]"
[bno055-1] [INFO] [1636651512.791274098] [bno055]:      mag_offset:             "[65460, 65182, 637]"
[bno055-1] [INFO] [1636651512.793762784] [bno055]:      gyr_offset:             "[2, 65535, 65535]"
[bno055-1] [INFO] [1636651512.796652196] [bno055]: Opening serial port: "/dev/ttyAMA1"...
[bno055-1] [INFO] [1636651512.820942188] [bno055]: Configuring device...
[bno055-1] [INFO] [1636651512.866787167] [bno055]: Bosch BNO055 IMU configuration complete.
[bno055-1] [WARN] [1636651512.889269662] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[bno055-1] [WARN] [1636651512.902735770] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[bno055-1] [WARN] [1636651512.914167770] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[bno055-1] [WARN] [1636651512.926148866] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[bno055-1] [WARN] [1636651512.937963776] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
[bno055-1] [WARN] [1636651512.949206051] [bno055]: Receiving sensor data failed with ZeroDivisionError:"float division by zero"
```

**Comment by flynneva** [comment]
Going to merge this for now and follow up another day on the remaining topics

**Pull request merged**
