### PR TITLE
[38] fix variance must be float array error

### LINKED ISSUE #38: Error orientation_covariance must be float array [9]
running the sensor on ros2-foxy i got this error for all covariance fields: 

 Receiving sensor data failed with AssertionError:"The 'orientation_covariance' field must be a set or sequence with length 9 and each value of type 'float'"

`        # TODO: make this an option to publish?
        imu_raw_msg.orientation_covariance = [
            self.param.variance_orientation, 0 , 0,
            0, self.param.variance_orientation, 0,
            0, 0, self.param.variance_orientation
        ]`

this must be corrected to for all variance msgs:

`
        xx = self.param.variance_orientation.value[0] # struct.unpack('!f', bytes.fromhex(str(self.param.variance_orientation)))[0]
        yy = self.param.variance_orientation.value[1] # struct.unpack('!f', bytes.fromhex(str(self.param.variance_orientation)))[0]
        zz = self.param.variance_orientation.value[0] # struct.unpack('!f', bytes.fromhex(str(self.param.variance_orientation)))[0]
        imu_raw_msg.orientation_covariance = [
            xx, 0.0 , 0.0,
            0.0, yy, 0.0,
            0.0, 0.0, zz
        ]
`

### PR DESCRIPTION
**Pull request by flynneva**
- closes #38 

Signed-off-by: Evan Flynn <evanflynn.msu@gmail.com>

### CODE REVIEW

**Comment by billymccafferty** [comment]
I believe the setting of imu_raw_msg.orientation_covariance should be as follows:

@flynneva , I think the correct resolution to correcting the settings of imu_raw_msg.orientation_covariance (line 149) is as follows:

```
imu_raw_msg.orientation_covariance = [
    self.param.variance_orientation.value[0], 0.0, 0.0,
    0.0, self.param.variance_orientation.value[1], 0.0,
    0.0, 0.0, self.param.variance_orientation.value[2]

```

With your changes, and fixing this, I'm seeing the following warning:
Receiving sensor data failed with TypeError:"unpackBytesToFloat() takes 2 positional arguments but 3 were given"

**Comment by flynneva** [comment]
@billymccafferty this is great!!!! thank you for your help testing it. With your feedback and a quick-fix to the new method I added (forgot to add `self` as an arg to the method) could you try this branch out again?

**Comment by billymccafferty** [comment]
There's a few other changes that need to be made...I'll make a PR off this branch. :)

**Comment by flynneva** [comment]
@billymccafferty oh wait we have to do the value thing for all of them dont we...apologies I am out of it today.

**Comment by billymccafferty** [comment]
Woohoo...after making the .value[n] and 0 -> 0.0 changes where needed, it's working...nice! Working on the PR now

**Comment by flynneva** [comment]
@billymccafferty ah just realized the others needed the same fix didn't they

**Pull request closed without merging**
